export const fileType = {
  "txt": "icon-txt",
  "html": "icon-html",
  "css": "icon-css",
  "js": "icon-JS",
  "mp3": "icon-mp3",
  "wav": "icon-mp3",
  "ogg": "icon-mp3",
  "mp4": "icon-mp4",
  "avi": "icon-mp4",
  "webm": "icon-mp4",
  "pdf": "icon-pdf",
  "doc": "icon-doc",
  "docx": "icon-doc",
  "xls": "icon-xls",
  "xlsx": "icon-xls",
  "ppt": "icon-ppt",
  "pptx": "icon-ppt",
  "zip": "icon-zip",
  "gz": "icon-zip",
  "tar": "icon-zip",
};
